### ISSUE TITLE
Evaluate Redux for state handling

### ISSUE THREAD

**Issue by tangerstein** [NovatecConsulting/novatec-k8s-panel#16]
Currently the state is propagated through the properties of React components. This leads to an increased complexity and can be better addressed by using Redux as state container.

**Comment by leoschur** [comment]
# Redux for Grafana Plugin?

## Pro

- clear overview of state from components
- additional debug tools (chromeplugin for redux)
- learning effect
- partial replacement possible

## Con

- high implementation effort
- states and actions are separated (files) from their origin/ user
- some states & callbacks might be difficult to implement in redux since their main goal is filtering the data (`showElements`, `handler()`)
- parameter for Simpelpanel are already handled by Grafana and cannot be used as state (options, data, width, height, timerange)
- no support for this redux usecase (no awnsers in Grafana forum to questions regarding redux + panel plugin)
- reduces reusability of components

Based on todays discussion and upper pros and cons we decided that in the current state of our applicaton we don´t need Redux for state handling. Instead we are looking into different solutions for our issue.
